FROM tiangolo/uvicorn-gunicorn:python3.11

COPY ./app/requirements.txt /app

RUN pip install -r /app/requirements.txt

COPY ./app /app

EXPOSE 8000
EXPOSE 3301

CMD [ "uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000" ]